using AnotherExternalMemoryLibrary;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace ActorConsole.Core.Memory
{
    public sealed class IW5 : Game
    {
        public static string TargetProcessName = "plutonium-bootstrapper-win32";
        public IW5() : base(Process.GetProcesses().First(p => p.ProcessName == TargetProcessName))
        {
        }

        public override IntPtrEx Cbuf_AddText { get; } = 0x545680;

        public override IntPtrEx LocalPlayerIsSpawnedAddress => Process.MainModule.BaseAddress + 0x500FB0;

        public override IntPtrEx LocalPlayerMapNameAddress => Process.MainModule.BaseAddress + 0x605870;

        public override IntPtrEx LocalPlayerNameAddress => Process.MainModule.BaseAddress + 0x56966C4;


        public override Type KillStreakEnum { get; } = typeof(Killstreak);
        public override Type CamoEnum { get; } = typeof(Camo);

        public enum Camo
        {
            none,
            classic,
            snow,
            multi,
            d_urban,
            hex,
            choco,
            snake,
            blue,
            red,
            autumn,
            gold,
            marine,
            winter,
        }

        public enum Killstreak
        {
            uav,
            double_uav,
            triple_uav,
            ac130,
            precision_airstrike,
            predator_missile,
            counter_uav,
            sentry,
            airdrop_assault,
            airdrop_sentry_minigun,
            airdrop_juggernaut,
            helicopter_flares,
            emp,
            littlebird_flock,
            stealth_airstrike,
            airdrop_trap,
            minigun_turret,
            escort_airdrop,
            osprey_gunner,
            deployable_vest,
            directional_uav,
            heli_sniper,
            ims,
            aastrike,
            remote_mortar,
            remote_mg_turret,
            airdrop_juggernaut_recon,
            uav_support,
            remote_uav,
            remote_tank,
            airdrop_remote_tank,
            sam_turret,
            helicopter,
            littlebird_support,
            specialty_longersprint_ks,
            specialty_fastreload_ks,
            specialty_scavenger_ks,
            specialty_blindeye_ks,
            specialty_paint_ks,
            specialty_hardline_ks,
            specialty_coldblooded_ks,
            specialty_quickdraw_ks,
            specialty_assists_ks,
            _specialty_blastshield_ks,
            specialty_detectexplosive_ks,
            specialty_autospot_ks,
            specialty_bulletaccuracy_ks,
            specialty_quieter_ks,
            specialty_stalker_ks
        }
        public static Precache Precache { get; } = new Precache()
        {
new KeyValuePair<string, Precache.AssetType>("pb_climbdown", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_climbup", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_back_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_back_loop", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_back_loop_assault", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_back_loop_grenade", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_back_loop_lmg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_back_loop_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_back_loop_shotgun", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_back_loop_smg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_back_loop_sniper", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_back_mg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_back_rpg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_back_shield", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_forward_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_forward_loop", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_forward_loop_assault", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_forward_loop_lmg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_forward_loop_shotgun", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_forward_loop_smg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_forward_loop_sniper", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_forward_loop_stickgrenade", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_forward_mg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_forward_rpg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_forward_shield", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_left_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_left_loop", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_left_loop_assault", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_left_loop_grenade", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_left_loop_lmg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_left_loop_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_left_loop_shotgun", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_left_loop_smg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_left_loop_sniper", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_left_mg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_left_rpg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_left_shield", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_right_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_right_loop", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_right_loop_assault", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_right_loop_grenade", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_right_loop_lmg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_right_loop_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_right_loop_shotgun", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_right_loop_smg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_right_loop_sniper", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_right_mg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_right_rpg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatrun_right_shield", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatwalk_back_loop_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatwalk_forward_loop_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatwalk_left_loop_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_combatwalk_right_loop_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch2prone", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_ads", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_ads_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_ads_rpg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_alert", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_alert_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_alert_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_alert_rpg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_alert_shield", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_bombplant", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_death_clutchchest", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_death_falltohands", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_death_fetal", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_death_flip", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_death_headshot_front", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_grenade_pullpin", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_grenade_throw", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_hold_idle", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_hold_run", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_hold_run_back", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_hold_run_left", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_hold_run_right", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_pain_holdstomach", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_remotecontroller", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_run_back", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_run_back_grenade", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_run_back_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_run_back_rpg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_run_forward", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_run_forward_grenade", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_run_forward_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_run_forward_rpg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_run_left", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_run_left_grenade", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_run_left_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_run_left_rpg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_run_right", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_run_right_grenade", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_run_right_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_run_right_rpg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_shellshock", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_shoot_run_back", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_shoot_run_forward", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_shoot_run_left", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_shoot_run_right", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_sprint", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_sprint_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_sprint_hold", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_sprint_mg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_sprint_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_sprint_rpg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_sprint_shield", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_walk_back_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_walk_back_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_walk_back_rpg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_walk_back_shield", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_walk_forward_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_walk_forward_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_walk_forward_rpg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_walk_forward_shield", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_walk_forward_unarmed", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_walk_left_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_walk_left_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_walk_left_rpg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_walk_left_shield", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_walk_right_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_walk_right_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_walk_right_rpg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouch_walk_right_shield", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouchrun_death_crumple", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_crouchrun_death_drop", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_deadhands_crawl_back", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_deadhands_crawl_forward", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_deadhands_crawl_left", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_deadhands_crawl_right", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_deadhands_idle", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_death_run_back", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_death_run_forward_crumple", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_death_run_left", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_death_run_onfront", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_death_run_right", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_death_run_stumble", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_dive_back", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_dive_back_impact", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_dive_front", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_dive_front_impact", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_dive_left", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_dive_left_impact", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_dive_right", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_dive_right_impact", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_explosion_death_b1", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_explosion_death_b2", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_explosion_death_b3", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_explosion_death_f1", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_explosion_death_l1", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_explosion_death_l2", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_explosion_death_r1", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_explosion_rundeath_b1", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_explosion_rundeath_b2", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_explosion_rundeath_f1", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_explosion_rundeath_f2", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_explosion_rundeath_f3", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_explosion_rundeath_l1", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_explosion_rundeath_r1", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_explosive_round_death_chesta", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_explosive_round_death_chestb", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_explosive_round_death_jaw", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_explosive_round_death_leg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_hold_idle", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_hold_run", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_hold_run_back", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_hold_run_left", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_hold_run_right", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_laststand_crawl", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_laststand_crawl_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_laststand_crawl_back", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_laststand_crawl_back_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_laststand_crawl_back_rpg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_laststand_crawl_back_shield", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_laststand_crawl_left", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_laststand_crawl_left_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_laststand_crawl_left_rpg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_laststand_crawl_left_shield", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_laststand_crawl_right", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_laststand_crawl_right_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_laststand_crawl_right_rpg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_laststand_crawl_right_shield", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_laststand_crawl_rpg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_laststand_crawl_shield", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_laststand_death", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_laststand_idle", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_laststand_idle_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_laststand_idle_rpg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_laststand_idle_shield", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_pistol_run_fast", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone2crouch", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone2crouch_shield", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone2crouchrun", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_aim", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_aim_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_aim_grenade", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_aim_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_aim_rpg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_aim_sniper", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_bombplant", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_crawl", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_crawl_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_crawl_back", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_crawl_back_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_crawl_back_hold", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_crawl_hold", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_crawl_left", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_crawl_left_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_crawl_left_hold", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_crawl_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_crawl_pistol_back", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_crawl_right", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_crawl_right_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_crawl_right_hold", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_death_quickdeath", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_grenade_crawl", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_grenade_crawl_back", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_grenade_crawl_left", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_grenade_crawl_right", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_hold", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_paina_holdchest", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_painb_holdhead", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_pistol_crawl_left", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_pistol_crawl_right", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_pullout_knife", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_prone_remotecontroller", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_rifle_idlea_ads", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_rifle_idleb_ads", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_run_fast", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_runjump_land", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_runjump_land_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_runjump_takeoff", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_runjump_takeoff_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_shield_grenade_pullpin", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_shield_knife_pullout", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_shotgun_death_back1", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_shotgun_death_back2", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_shotgun_death_front", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_shotgun_death_legs", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_shotgun_death_spinl", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_shotgun_death_spinr", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_sprint", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_sprint_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_sprint_assault", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_sprint_gundown", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_sprint_hold", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_sprint_lmg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_sprint_mg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_sprint_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_sprint_rpg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_sprint_shield", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_sprint_shotgun", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_sprint_smg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_sprint_sniper", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand__shoot_ads_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_ads", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_ads_mg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_ads_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_ads_rpg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_alert", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_alert_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_alert_mg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_alert_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_alert_rpg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_alert_shield", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_bombplant", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_death_chest_blowback", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_death_chest_spin", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_death_frontspin", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_death_head_collapse", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_death_head_straight_back", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_death_headchest_topple", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_death_headshot_slowfall", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_death_kickup", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_death_leg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_death_leg_kickup", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_death_legs", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_death_lowerback", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_death_neckdeath", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_death_neckdeath_thrash", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_death_nervedeath", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_death_shoulder_stumble", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_death_shoulderback", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_death_stumbleforward", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_death_tumbleback", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_grenade_pullpin", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_grenade_throw", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_pullout_knife", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_remotecontroller", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_shellshock", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_shoot_walk_back", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_shoot_walk_forward", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_shoot_walk_forward_unarmed", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_shoot_walk_left", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stand_shoot_walk_right", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_standjump_land", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_standjump_land_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_standjump_takeoff", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_standjump_takeoff_pistol", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stumble_back", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stumble_forward", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stumble_grenade_back", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stumble_grenade_forward", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stumble_grenade_left", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stumble_grenade_right", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stumble_left", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stumble_pistol_back", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stumble_pistol_forward", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stumble_pistol_left", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stumble_pistol_right", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stumble_pistol_walk_back", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stumble_pistol_walk_forward", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stumble_pistol_walk_left", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stumble_pistol_walk_right", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stumble_right", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stumble_walk_back", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stumble_walk_forward", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stumble_walk_left", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_stumble_walk_right", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_walk_back_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_walk_back_rpg_ads", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_walk_back_shield", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_walk_forward_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_walk_forward_mg", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_walk_forward_rpg_ads", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_walk_forward_shield", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_walk_left_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_walk_left_rpg_ads", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_walk_left_shield", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_walk_right_akimbo", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_walk_right_rpg_ads", Precache.AssetType.xanim),
new KeyValuePair<string, Precache.AssetType>("pb_walk_right_shield", Precache.AssetType.xanim),

        };

        public override Type KillStreakModelEnum { get; } = typeof(KillstreakModel);
        public enum KillstreakModel
        {
            vehicle_ac130_coop,
            vehicle_ac130_low_mp,
            vehicle_apache_mp,
            vehicle_av8b_harrier_jet_mp,
            vehicle_av8b_harrier_jet_opfor_mp,
            vehicle_b2_bomber,
            vehicle_cobra_helicopter_fly_low,
            vehicle_little_bird_armed,
            vehicle_mi24p_hind_mp,
            vehicle_mig29_desert,
            vehicle_pavelow,
            vehicle_pavelow_opfor,
            vehicle_phantom_ray,
            vehicle_predator_b,
            vehicle_remote_uav,
            vehicle_uav_static_mp,
            vehicle_uaz_fabric_dsr,
            vehicle_uaz_van,
            vehicle_ugv_talon_mp,
            vehicle_v22_osprey_body_mp
        }
    }
}
